Token-based authorization.
wtsi-npg/npg_porch pull request #32
Opened 2022-03-08 18:09 UTC by mgcam

Token-based authorization, initially for the pipeline
endpoints only, the pipeline the token belongs to is not
validated in the context of the request.

2022-03-09 12:43 UTC, nerdstrike requested changes
I'm generally fine with this. What is it you intend to happen to permissions on get_pipeline?

Might be interesting to see if we could make a suitable `@decorator` for admin routes

2022-03-09 19:06 UTC, mgcam commented on server/npg/porchdb/auth.py
> +            prog = re.compile(r'\w{32}', flags=re.ASCII)
Improved

2022-03-09 19:07 UTC, mgcam commented
> What is it you intend to happen to permissions on get_pipeline?
Any valid token should work.

> Might be interesting to see if we could make a suitable `@decorator` for admin routes
We do not have many at the moment, will leave this for future

2022-03-10 13:48 UTC, nerdstrike approved these changes
I like this a lot more now!

2022-03-10 15:34 UTC, nerdstrike commented
Redudant with #33

2022-03-10 15:34 UTC, closed without merging